# Generated by Django 5.2.17 on 2026-10-05 16:20

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_image_url_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(validators=[books.validators.BadLanguageValidator('The provided description contains bad langauge!')]),
        ),
    ]
