# Generated by Django 5.2.11 on 2026-02-17 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Ensure this value contains only letters, numbers, and underscore.', regex='^[A-Za-z0-9_]+$')]),
        ),
    ]
