# Generated by Django 5.0.4 on 2024-07-18 13:37

from django.db import migrations
from django.utils import timezone


def forwards_func(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    Review = apps.get_model("reviews", "Review")

    # Create Books
    book1 = Book.objects.create(
        title="The Hitchhiker's Guide to the Galaxy",
        price=12.99,
        isbn="9780345391",
        genre="Science",
        publishing_date=timezone.now(),
        description="A hilarious science fiction adventure.",
        image_url="http://example.com/hitchhiker.jpg",
        pages=224,
        publisher="Pan Books",
        slug="9780345391"
    )

    book2 = Book.objects.create(
        title="The Lord of the Rings",
        price=29.99,
        isbn="9780618640",
        genre="Fantasy",
        publishing_date=timezone.now(),
        description="An epic fantasy novel by J.R.R. Tolkien.",
        image_url="http://example.com/lotr.jpg",
        pages=1178,
        publisher="Allen & Unwin",
        slug="9780618640"
    )

    book3 = Book.objects.create(
        title="Pride and Prejudice",
        price=9.99,
        isbn="9780141439",
        genre="Fiction",
        publishing_date=timezone.now(),
        description="A classic romance novel by Jane Austen.",
        image_url="http://example.com/pride.jpg",
        pages=432,
        publisher="T. Egerton, Whitehall",
        slug="9780141439"
    )

    book4 = Book.objects.create(
        title="To Kill a Mockingbird",
        price=14.99,
        isbn="9780446310",
        genre="Fiction",
        publishing_date=timezone.now(),
        description="A novel by Harper Lee published in 1960.",
        image_url="http://example.com/mockingbird.jpg",
        pages=324,
        publisher="J. B. Lippincott & Co.",
        slug="9780446310"
    )

    book5 = Book.objects.create(
        title="1984",
        price=11.99,
        isbn="9780451524",
        genre="Non-Fiction",
        publishing_date=timezone.now(),
        description="A dystopian social science fiction novel by George Orwell.",
        image_url="http://example.com/1984.jpg",
        pages=328,
        publisher="Secker & Warburg",
        slug="9780451524"
    )

    # Create Reviews
    Review.objects.create(author="Alice", body="A must-read for any sci-fi fan!", rating=4.5, book=book1)
    Review.objects.create(author="Bob", body="Hilarious and thought-provoking.", rating=5.0, book=book1)
    Review.objects.create(author="Charlie", body="I didn't get the hype.", rating=3.0, book=book1)

    Review.objects.create(author="Alice", body="An absolute masterpiece of fantasy.", rating=5.0, book=book2)
    Review.objects.create(author="Bob", body="A bit long, but worth it.", rating=4.0, book=book2)
    Review.objects.create(author="Charlie", body="The world-building is incredible.", rating=5.0, book=book2)

    Review.objects.create(author="Alice", body="A timeless classic.", rating=5.0, book=book3)
    Review.objects.create(author="Bob", body="Mr. Darcy is the best!", rating=4.5, book=book3)
    Review.objects.create(author="Charlie", body="A bit slow for my taste.", rating=3.5, book=book3)

    Review.objects.create(author="Alice", body="A powerful and moving story.", rating=5.0, book=book4)
    Review.objects.create(author="Bob", body="Atticus Finch is a hero.", rating=5.0, book=book4)
    Review.objects.create(author="Charlie", body="Made me think about justice.", rating=4.5, book=book4)

    Review.objects.create(author="Alice", body="A chilling look at a possible future.", rating=5.0, book=book5)
    Review.objects.create(author="Bob", body="More relevant than ever.", rating=5.0, book=book5)
    Review.objects.create(author="Charlie", body="A bit depressing, but important.", rating=4.0, book=book5)


def backwards_func(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    Review = apps.get_model("reviews", "Review")

    # Nuke all books and reviews
    Book.objects.all().delete()
    Review.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_alter_book_slug'),
        ('reviews', '0002_alter_review_book'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]