# Generated by Django 5.2.8 on 2026-01-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='books.tag'),
        ),
    ]
