from django.db import migrations
from django.utils.text import slugify


BOOKS = [
    {
        "title": "The Hobbit",
        "price": "14.99",
        "isbn": "0547928220",
        "genre": "Fantasy",
        "publishing_date": "1937-09-21",
        "description": "A quiet hobbit is swept into an unexpected journey with dwarves, a wizard, and a very dangerous dragon.",
        "pages": 310,
        "publisher": "HarperCollins",
    },
    {
        "title": "The Fellowship of the Ring",
        "price": "18.50",
        "isbn": "0618346252",
        "genre": "Fantasy",
        "publishing_date": "1954-07-29",
        "description": "A small company sets out from the Shire carrying a ring that no kingdom is strong enough to keep safely.",
        "pages": 423,
        "publisher": "HarperCollins",
    },
    {
        "title": "A Game of Thrones",
        "price": "21.00",
        "isbn": "0553103547",
        "genre": "Fantasy",
        "publishing_date": "1996-08-01",
        "description": "Noble houses trade favors, armies, and betrayals while a far older threat gathers beyond the northern wall.",
        "pages": 694,
        "publisher": "Bantam Books",
    },
    {
        "title": "Harry Potter and the Philosopher's Stone",
        "price": "12.75",
        "isbn": "0747532699",
        "genre": "Fantasy",
        "publishing_date": "1997-06-26",
        "description": "An orphaned boy learns he is a wizard and spends his first year at school uncovering what his parents left behind.",
        "pages": 223,
        "publisher": "Bloomsbury",
    },
    {
        "title": "The Name of the Wind",
        "price": "17.25",
        "isbn": "0756404746",
        "genre": "Fantasy",
        "publishing_date": "2007-03-27",
        "description": "An innkeeper with a hidden past tells the story of how he became the most talked about magician of his age.",
        "pages": 662,
        "publisher": "DAW Books",
    },
    {
        "title": "Mistborn: The Final Empire",
        "price": "16.40",
        "isbn": "0765311771",
        "genre": "Fantasy",
        "publishing_date": "2006-07-17",
        "description": "A street thief joins a crew of rebels who use metal-fueled magic to plan a heist against an immortal ruler.",
        "pages": 541,
        "publisher": "Tor Books",
    },
    {
        "title": "1984",
        "price": "9.99",
        "isbn": "0451524934",
        "genre": "Fiction",
        "publishing_date": "1949-06-08",
        "description": "A clerk who edits the past for a living starts keeping a diary, which is the first crime in a state that watches everything.",
        "pages": 328,
        "publisher": "Secker & Warburg",
    },
    {
        "title": "Brave New World",
        "price": "11.30",
        "isbn": "0060850523",
        "genre": "Fiction",
        "publishing_date": "1932-01-01",
        "description": "A society engineered for comfort has removed pain, family, and choice, until one outsider refuses the trade.",
        "pages": 311,
        "publisher": "Chatto & Windus",
    },
    {
        "title": "To Kill a Mockingbird",
        "price": "13.20",
        "isbn": "0061120081",
        "genre": "Fiction",
        "publishing_date": "1960-07-11",
        "description": "A lawyer in a small Alabama town defends an innocent man, and his children watch the place they love show its worst side.",
        "pages": 281,
        "publisher": "J. B. Lippincott & Co.",
    },
    {
        "title": "The Great Gatsby",
        "price": "10.50",
        "isbn": "0743273567",
        "genre": "Fiction",
        "publishing_date": "1925-04-10",
        "description": "A wealthy host throws enormous parties on Long Island for the sake of one guest who may never arrive.",
        "pages": 180,
        "publisher": "Scribner",
    },
    {
        "title": "The Catcher in the Rye",
        "price": "11.90",
        "isbn": "0316769487",
        "genre": "Fiction",
        "publishing_date": "1951-07-16",
        "description": "Three restless days in New York told by a teenager who has just been expelled and is not ready to go home.",
        "pages": 277,
        "publisher": "Little, Brown and Company",
    },
    {
        "title": "Fahrenheit 451",
        "price": "12.10",
        "isbn": "1451673310",
        "genre": "Fiction",
        "publishing_date": "1953-10-19",
        "description": "A fireman whose job is burning books begins to hide them, and slowly loses his place in a world built on distraction.",
        "pages": 194,
        "publisher": "Ballantine Books",
    },
    {
        "title": "The Road",
        "price": "14.20",
        "isbn": "0307387895",
        "genre": "Fiction",
        "publishing_date": "2006-09-26",
        "description": "A father and son push a shopping cart south through burned country, keeping each other alive one day at a time.",
        "pages": 287,
        "publisher": "Alfred A. Knopf",
    },
    {
        "title": "Never Let Me Go",
        "price": "13.75",
        "isbn": "1400078776",
        "genre": "Fiction",
        "publishing_date": "2005-03-03",
        "description": "Three friends raised at a sheltered English boarding school slowly work out what their education was actually for.",
        "pages": 288,
        "publisher": "Faber and Faber",
    },
    {
        "title": "Norwegian Wood",
        "price": "15.60",
        "isbn": "0375704027",
        "genre": "Fiction",
        "publishing_date": "1987-09-04",
        "description": "A student in 1960s Tokyo is pulled between a fragile first love and a woman who wants him to live in the present.",
        "pages": 296,
        "publisher": "Kodansha",
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "price": "22.40",
        "isbn": "0062316095",
        "genre": "History",
        "publishing_date": "2014-02-10",
        "description": "A sweeping account of how shared stories let one species of ape organize itself into empires, markets, and religions.",
        "pages": 443,
        "publisher": "Harper",
    },
    {
        "title": "Guns, Germs, and Steel",
        "price": "19.80",
        "isbn": "0393317552",
        "genre": "History",
        "publishing_date": "1997-03-01",
        "description": "An argument that geography and crops, not talent, decided which societies expanded and which were conquered.",
        "pages": 480,
        "publisher": "W. W. Norton & Company",
    },
    {
        "title": "SPQR: A History of Ancient Rome",
        "price": "24.90",
        "isbn": "1846683807",
        "genre": "History",
        "publishing_date": "2015-10-20",
        "description": "A thousand years of Rome told through its citizens, its arguments about power, and the evidence they left behind.",
        "pages": 606,
        "publisher": "Profile Books",
    },
    {
        "title": "The Silk Roads",
        "price": "23.15",
        "isbn": "1408839970",
        "genre": "History",
        "publishing_date": "2015-08-27",
        "description": "World history retold from the trade routes of Central Asia, where goods, faiths, and plagues all moved together.",
        "pages": 636,
        "publisher": "Bloomsbury",
    },
    {
        "title": "The Diary of a Young Girl",
        "price": "10.99",
        "isbn": "0553296981",
        "genre": "History",
        "publishing_date": "1947-06-25",
        "description": "Two years of hiding in an Amsterdam annex, written by a teenager who kept describing ordinary life anyway.",
        "pages": 283,
        "publisher": "Contact Publishing",
    },
    {
        "title": "A Brief History of Time",
        "price": "16.99",
        "isbn": "0553380168",
        "genre": "Science",
        "publishing_date": "1988-04-01",
        "description": "Black holes, the big bang, and the shape of time explained without a single equation getting in the way.",
        "pages": 212,
        "publisher": "Bantam Books",
    },
    {
        "title": "Cosmos",
        "price": "18.30",
        "isbn": "0345539435",
        "genre": "Science",
        "publishing_date": "1980-10-12",
        "description": "A tour from the first cells to distant galaxies, arguing that science is a way of thinking before it is a body of facts.",
        "pages": 365,
        "publisher": "Random House",
    },
    {
        "title": "The Selfish Gene",
        "price": "15.45",
        "isbn": "0198788606",
        "genre": "Science",
        "publishing_date": "1976-01-01",
        "description": "Evolution seen from the point of view of the gene, which reframes cooperation, conflict, and family in one move.",
        "pages": 224,
        "publisher": "Oxford University Press",
    },
    {
        "title": "The Gene: An Intimate History",
        "price": "21.70",
        "isbn": "1476733503",
        "genre": "Science",
        "publishing_date": "2016-05-17",
        "description": "The story of heredity from monastery peas to gene editing, with the ethical questions each discovery reopened.",
        "pages": 592,
        "publisher": "Scribner",
    },
    {
        "title": "Astrophysics for People in a Hurry",
        "price": "13.99",
        "isbn": "0393609391",
        "genre": "Science",
        "publishing_date": "2017-05-02",
        "description": "Short chapters covering dark matter, exoplanets, and the laws that hold everywhere, written for a busy commute.",
        "pages": 224,
        "publisher": "W. W. Norton & Company",
    },
    {
        "title": "Thinking, Fast and Slow",
        "price": "20.25",
        "isbn": "0374533555",
        "genre": "Non-Fiction",
        "publishing_date": "2011-10-25",
        "description": "Decades of research on the two systems behind our judgments, and the reliable ways both of them go wrong.",
        "pages": 499,
        "publisher": "Farrar, Straus and Giroux",
    },
    {
        "title": "Atomic Habits",
        "price": "17.60",
        "isbn": "0735211299",
        "genre": "Non-Fiction",
        "publishing_date": "2018-10-16",
        "description": "A practical system for changing behavior by shaping small routines and the environment that triggers them.",
        "pages": 320,
        "publisher": "Avery",
    },
    {
        "title": "Educated",
        "price": "16.80",
        "isbn": "0399590501",
        "genre": "Non-Fiction",
        "publishing_date": "2018-02-20",
        "description": "A memoir of growing up outside school and government records, and of what a first classroom cost the author at home.",
        "pages": 334,
        "publisher": "Random House",
    },
    {
        "title": "Quiet: The Power of Introverts",
        "price": "15.90",
        "isbn": "0307352153",
        "genre": "Non-Fiction",
        "publishing_date": "2012-01-24",
        "description": "Why workplaces and classrooms reward talking, and what gets lost when quieter people are asked to perform.",
        "pages": 333,
        "publisher": "Crown Publishing Group",
    },
    {
        "title": "The Immortal Life of Henrietta Lacks",
        "price": "18.10",
        "isbn": "1400052181",
        "genre": "Non-Fiction",
        "publishing_date": "2010-02-02",
        "description": "Cells taken without consent in 1951 built a research industry, while the family they came from could not afford care.",
        "pages": 381,
        "publisher": "Crown Publishing Group",
    },
    {
        "title": "The Girl with the Dragon Tattoo",
        "price": "14.45",
        "isbn": "0307454541",
        "genre": "Mystery",
        "publishing_date": "2005-08-01",
        "description": "A disgraced journalist and a brilliant hacker reopen a disappearance that a wealthy family never wanted solved.",
        "pages": 465,
        "publisher": "Norstedts Förlag",
    },
    {
        "title": "Gone Girl",
        "price": "13.85",
        "isbn": "0307588378",
        "genre": "Mystery",
        "publishing_date": "2012-06-05",
        "description": "A wife vanishes on her fifth anniversary, and every new detail about the marriage makes the husband look worse.",
        "pages": 415,
        "publisher": "Crown Publishing Group",
    },
    {
        "title": "The Murder of Roger Ackroyd",
        "price": "11.75",
        "isbn": "0007527526",
        "genre": "Mystery",
        "publishing_date": "1926-06-01",
        "description": "A retired detective in a quiet village takes one last case, narrated by the local doctor who assists him.",
        "pages": 312,
        "publisher": "William Collins & Sons",
    },
    {
        "title": "And Then There Were None",
        "price": "12.55",
        "isbn": "0062073486",
        "genre": "Mystery",
        "publishing_date": "1939-11-06",
        "description": "Ten strangers are invited to an island by a host who never appears, and the guest list begins to shorten.",
        "pages": 272,
        "publisher": "Collins Crime Club",
    },
    {
        "title": "The Hound of the Baskervilles",
        "price": "9.60",
        "isbn": "0140437863",
        "genre": "Mystery",
        "publishing_date": "1902-03-25",
        "description": "A family legend about a beast on the moor turns into a case that Holmes works largely from the shadows.",
        "pages": 256,
        "publisher": "George Newnes",
    },
]


def seed_books(apps, schema_editor):
    Book = apps.get_model("books", "Book")

    for book in BOOKS:
        slug = slugify(f"{book['title']}-{book['publisher']}")

        Book.objects.update_or_create(
            isbn=book["isbn"],
            defaults={
                **book,
                "slug": slug,
                "image_url": f"https://picsum.photos/seed/{slug}/600/400",
            },
        )


def remove_seeded_books(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    Book.objects.filter(
        isbn__in=[book["isbn"] for book in BOOKS],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_books, remove_seeded_books),
    ]
