# Generated by Django 5.2.11 on 2026-02-09 17:40

import django.core.validators
import travelers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[travelers.validators.validate_email_domain])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('country', models.CharField(choices=[('BG', 'Bulgaria'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('OTHER', 'Other')], max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
